package com.ts.CXFClient;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * MedicarePaymentService service = new MedicarePaymentService();
 * MedicarePayment portType = service.getMedicarePaymentPort();
 * portType.getSectionRefund(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "MedicarePaymentService", targetNamespace = "http://www.ts.com/services/MedicarePayment", wsdlLocation = "http://127.0.0.1:8081/services/medicarePayment?wsdl")
public class MedicarePaymentService extends Service {

	private final static URL MEDICAREPAYMENTSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.ts.CXFClient.MedicarePaymentService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.ts.CXFClient.MedicarePaymentService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://127.0.0.1:8081/services/medicarePayment?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:8081/services/medicarePayment?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		MEDICAREPAYMENTSERVICE_WSDL_LOCATION = url;
	}

	public MedicarePaymentService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public MedicarePaymentService() {
		super(MEDICAREPAYMENTSERVICE_WSDL_LOCATION, new QName(
				"http://www.ts.com/services/MedicarePayment",
				"MedicarePaymentService"));
	}

	/**
	 * 
	 * @return returns MedicarePayment
	 */
	@WebEndpoint(name = "MedicarePaymentPort")
	public MedicarePayment getMedicarePaymentPort() {
		return super.getPort(new QName(
				"http://www.ts.com/services/MedicarePayment",
				"MedicarePaymentPort"), MedicarePayment.class);
	}

}
