package com.ts.CXFClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "MedicarePayment", targetNamespace = "http://www.ts.com/services/MedicarePayment")
public interface MedicarePayment {

	/**
	 * 
	 * @param arg0
	 * @return returns com.ts.CXFClient.I31OutputSectionRefundBean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getSectionRefund", targetNamespace = "http://www.ts.com/services/MedicarePayment", className = "com.ts.CXFClient.GetSectionRefund")
	@ResponseWrapper(localName = "getSectionRefundResponse", targetNamespace = "http://www.ts.com/services/MedicarePayment", className = "com.ts.CXFClient.GetSectionRefundResponse")
	public I31OutputSectionRefundBean getSectionRefund(
			@WebParam(name = "arg0", targetNamespace = "") I31InputSectionRefundBean arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns com.ts.CXFClient.I28OutputSectionAccountsbean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getSectionAccounts", targetNamespace = "http://www.ts.com/services/MedicarePayment", className = "com.ts.CXFClient.GetSectionAccounts")
	@ResponseWrapper(localName = "getSectionAccountsResponse", targetNamespace = "http://www.ts.com/services/MedicarePayment", className = "com.ts.CXFClient.GetSectionAccountsResponse")
	public I28OutputSectionAccountsbean getSectionAccounts(
			@WebParam(name = "arg0", targetNamespace = "") I28InputSectionAccountsBean arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns com.ts.CXFClient.I22OutputGetInfoPersonBean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getPersonalInformation", targetNamespace = "http://www.ts.com/services/MedicarePayment", className = "com.ts.CXFClient.GetPersonalInformation")
	@ResponseWrapper(localName = "getPersonalInformationResponse", targetNamespace = "http://www.ts.com/services/MedicarePayment", className = "com.ts.CXFClient.GetPersonalInformationResponse")
	public I22OutputGetInfoPersonBean getPersonalInformation(
			@WebParam(name = "arg0", targetNamespace = "") I22InputGetInfoPersonBean arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns com.ts.CXFClient.I41OutputHospitalDetailQueryBean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getHospitalDetailQuery", targetNamespace = "http://www.ts.com/services/MedicarePayment", className = "com.ts.CXFClient.GetHospitalDetailQuery")
	@ResponseWrapper(localName = "getHospitalDetailQueryResponse", targetNamespace = "http://www.ts.com/services/MedicarePayment", className = "com.ts.CXFClient.GetHospitalDetailQueryResponse")
	public I41OutputHospitalDetailQueryBean getHospitalDetailQuery(
			@WebParam(name = "arg0", targetNamespace = "") I41InputHospitalDetailQueryBean arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns com.ts.CXFClient.I36OutputHospitalAccountsBean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getHospitalAccounts", targetNamespace = "http://www.ts.com/services/MedicarePayment", className = "com.ts.CXFClient.GetHospitalAccounts")
	@ResponseWrapper(localName = "getHospitalAccountsResponse", targetNamespace = "http://www.ts.com/services/MedicarePayment", className = "com.ts.CXFClient.GetHospitalAccountsResponse")
	public I36OutputHospitalAccountsBean getHospitalAccounts(
			@WebParam(name = "arg0", targetNamespace = "") I36InputHospitalAccountsBean arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns com.ts.CXFClient.I46OutputPreSectionStateQueryBean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getPreSectionStateQuery", targetNamespace = "http://www.ts.com/services/MedicarePayment", className = "com.ts.CXFClient.GetPreSectionStateQuery")
	@ResponseWrapper(localName = "getPreSectionStateQueryResponse", targetNamespace = "http://www.ts.com/services/MedicarePayment", className = "com.ts.CXFClient.GetPreSectionStateQueryResponse")
	public I46OutputPreSectionStateQueryBean getPreSectionStateQuery(
			@WebParam(name = "arg0", targetNamespace = "") I46InputPreSectionStateQueryBean arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns com.ts.CXFClient.I43OutputTradeResultsQueryBean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getTradeResultsQuery", targetNamespace = "http://www.ts.com/services/MedicarePayment", className = "com.ts.CXFClient.GetTradeResultsQuery")
	@ResponseWrapper(localName = "getTradeResultsQueryResponse", targetNamespace = "http://www.ts.com/services/MedicarePayment", className = "com.ts.CXFClient.GetTradeResultsQueryResponse")
	public I43OutputTradeResultsQueryBean getTradeResultsQuery(
			@WebParam(name = "arg0", targetNamespace = "") I43InputTradeResultsQueryBean arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns com.ts.CXFClient.I49OutputTradeConfirmBean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getTradeConfirm", targetNamespace = "http://www.ts.com/services/MedicarePayment", className = "com.ts.CXFClient.GetTradeConfirm")
	@ResponseWrapper(localName = "getTradeConfirmResponse", targetNamespace = "http://www.ts.com/services/MedicarePayment", className = "com.ts.CXFClient.GetTradeConfirmResponse")
	public I49OutputTradeConfirmBean getTradeConfirm(
			@WebParam(name = "arg0", targetNamespace = "") I49InputTradeConfirmBean arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns com.ts.CXFClient.I27OutputPreSectionAccountsBean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getPreSectionAccounts", targetNamespace = "http://www.ts.com/services/MedicarePayment", className = "com.ts.CXFClient.GetPreSectionAccounts")
	@ResponseWrapper(localName = "getPreSectionAccountsResponse", targetNamespace = "http://www.ts.com/services/MedicarePayment", className = "com.ts.CXFClient.GetPreSectionAccountsResponse")
	public I27OutputPreSectionAccountsBean getPreSectionAccounts(
			@WebParam(name = "arg0", targetNamespace = "") I27InputPreSectionAccountsBean arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns com.ts.CXFClient.I34OutputPreInHospitalAccountsBean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getPreInHospitalAccounts", targetNamespace = "http://www.ts.com/services/MedicarePayment", className = "com.ts.CXFClient.GetPreInHospitalAccounts")
	@ResponseWrapper(localName = "getPreInHospitalAccountsResponse", targetNamespace = "http://www.ts.com/services/MedicarePayment", className = "com.ts.CXFClient.GetPreInHospitalAccountsResponse")
	public I34OutputPreInHospitalAccountsBean getPreInHospitalAccounts(
			@WebParam(name = "arg0", targetNamespace = "") I34InputPreInHospitalAccountsBean arg0);

}
